[metadata]
name = dls_slow_feedbacks
description = Slow feedback systems for the DLS storage ring
long-description = file: README.rst
author = High Level Apps
license = Apache License 2.0
url = https://gitlab.diamond.ac.uk/controls/python3/dls_slow_feedbacks
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    Topic :: Software Development :: Build Tools
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
keywords = accelerator physics

[options]
packages =
    dls_slow_feedbacks
install_requires =
    pytac==0.5.0
    cothread
    softioc

[options.package_data]
dls_slow_feedbacks =
    opi
    opi/*.edl
    opi/*.opi

[options.entry_points]
console_scripts = 
    start-ioc = dls_slow_feedbacks.ioc:main
    start-css = dls_slow_feedbacks.start_css:main
    tune-feedback-offsets = dls_slow_feedbacks.tunefb_offsets:main
    start-sofb-edm = dls_slow_feedbacks.start_edm:sofb_gui
    start-vefb-edm = dls_slow_feedbacks.start_edm:vefb_gui
    start-tunefb-edm = dls_slow_feedbacks.start_edm:tunefb_gui

[mypy]
# Ignore missing stubs for modules we use
ignore_missing_imports = True

[isort]
profile=black
float_to_top=true
skip=setup.py,conf.py,build

[flake8]
# Make flake8 respect black's line length (default 88),
max-line-length = 88
extend-ignore =
    E203, # See https://github.com/PyCQA/pycodestyle/issues/373
    F811, # support typing.overload decorator
    F722, # allow Annotated[typ, some_func("some string")]

[tool:pytest]
# Run pytest with all our checkers, and don't spam us with massive tracebacks on error
addopts =
    --tb=native -vv --flake8 --black --mypy --doctest-modules --doctest-glob="*.rst"
     --cov=dls_slow_feedbacks --cov-report term --cov-report xml:cov.xml

[coverage:run]
# This is covered in the versiongit test suite so exclude it here
omit = */_version_git.py
