[metadata]
name = dls_slow_feedbacks
version = 0.0.1
description = Slow feedback systems for the DLS storage ring
long-description = file: README.rst
author = High Level Apps
license = Apache License 2.0
url = https://gitlab.diamond.ac.uk/controls/python3/dls_slow_feedbacks
classifiers =
    Development Status :: 3 - Alpha
    Intended Audience :: Developers
    Topic :: Software Development :: Build Tools
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
keywords = accelerator physics

[options]
packages =
    dls_slow_feedbacks
install_requires =
    pytac
    cothread
    softioc

[options.entry_points]
console_scripts = 
    start-ioc = dls_slow_feedbacks.ioc:main
    tune-feedback-offsets = dls_slow_feedbacks.tunefb_offsets:main

[flake8]
# Make flake8 respect black's line length (default 88),
max-line-length = 88
exclude =
    .git
    atip/junk
    venv*
    docs
    build
