#!/bin/sh

PYIOC_VERSION=2-4
PYIOC=/dls_sw/prod/R3.14.11/support/pythonSoftIoc/$PYIOC_VERSION/pythonIoc

export EPICS_BASE=/dls_sw/epics/R3.14.11/base

# If run with argument assume debug mode
[ -n "$1" ]  &&  export EPICS_CAS_SERVER_PORT=6064

cd "$(dirname "$0")/python"
exec $PYIOC feedback_ioc.py "$@"
