#!/bin/sh

PYIOC_VERSION=2-14
PYIOC=/dls_sw/prod/R3.14.12.7/support/pythonIoc/$PYIOC_VERSION/pythonIoc

# If run with argument assume debug mode
[ -n "$1" ]  &&  export EPICS_CAS_SERVER_PORT=6064

cd "$(dirname "$0")/python"
exec $PYIOC feedback_ioc.py "$@"
